spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0
  data:
    redis:
      cluster:
        nodes:
          - 192.168.0.150:6379
          - 192.168.0.150:6380
          - 192.168.0.150:6381
          - 192.168.0.150:6382
          - 192.168.0.150:6383
          - 192.168.0.150:6384
        max-redirects: 6
